# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

archive_name = StructureControlUtility
mod_id = hardermonsterboats
mod_group=com.mactso.hardermonsterboats
mod_version=59.7.0
archive_name=forge-HarderMonsterBoats
# Minecraft & Forge versions
mc_version=1.21.9
forge_version=59.0.5
mappings_channel = official
mappings_version = 1.21.9

