modLoader="javafml"
loaderVersion="[54,)"
license="MIT License"
[[mods]]
modId="hardermonsterboats"
version="${file.jarVersion}"
displayName="Harder Monster Boats"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-monster-boats"
displayTest="IGNORE_SERVER_VERSION"
updateJSONURL="https://github.com/mactso/HarderMonsterBoats/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='hardermonsterboats.'
[[dependencies.hardermonsterboats]]
    modId="forge"
    mandatory=true
    versionRange="[54,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.hardermonsterboats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.4,1.22)"
    ordering="NONE"
    side="SERVER"
# side="BOTH", "CLIENT?", "SERVER"

