modLoader="javafml"
loaderVersion="[59,)"
license="MIT"

[[mods]]
modId="hardermonsterboats"
version="59.7.0"
displayName="Harder Monster Boats"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-monster-boats"
displayTest="IGNORE_SERVER_VERSION"
updateJSONURL="https://github.com/mactso/HarderMonsterBoats/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='hardermonsterboats.'
[[dependencies.hardermonsterboats]]
modId="forge"
mandatory=true
versionRange="[59,)"
ordering="NONE"
side="BOTH"

[[dependencies.hardermonsterboats]]
modId="minecraft"
mandatory=true
versionRange="[1.21.9,1.22)"
ordering="NONE"
side="BOTH"