modLoader="javafml"
loaderVersion="[46,)"
license="MIT License"
[[mods]]
modId="hardermonsterboats"
version="${file.jarVersion}"
displayName="Harder Monster Boats"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-monster-boats"
updateJSONURL="https://github.com/mactso/HarderMonsterBoats/raw/main/update.json"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='hardermonsterboats.'
[[dependencies.hardermonsterboats]]
    modId="forge"
    mandatory=true
    versionRange="[46,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.hardermonsterboats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="SERVER"


