# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
loaderVersion="[55,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
license="MIT"
[[mods]]
modId="hardermonsterboats"
version="${file.jarVersion}"
displayName="Harder Monster Boats"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-monster-boats"
displayTest="IGNORE_SERVER_VERSION"
logoFile="Logo.png"
authors="MacTso, Lupicus"
description='hardermonsterboats.'
[[dependencies.hardermonsterboats]]
    modId="forge"
    mandatory=true
    versionRange="[55,)"
    ordering="NONE"
    side="SERVER"

[[dependencies.hardermonsterboats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.5,1.22)"
    ordering="NONE"
    side="SERVER"
# side="BOTH", "CLIENT?", "SERVER"

