modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"
[[mods]]
modId="hardermonsterboats"
version="${file.jarVersion}"
displayName="Harder Monster Boats"
displayURL="https://www.curseforge.com/minecraft/mc-mods/harder-monster-boats"
displayTest="IGNORE_SERVER_VERSION"
logoFile="logo.png"
authors="Lupicus, MacTso"
description='''Harder Monster Boats'''
[[dependencies.hardermonsterboats]]
    modId="neoforge"
    type="required"
    versionRange="[21,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.hardermonsterboats]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
